CREATE TABLE "GCG_4666_COMMSTRUCT"(
 "IH_COMM_LESSPER" DOUBLE,
 "IH_COMM_LESS" DOUBLE,
 "IH_COMM_GREATERPER" DOUBLE,
 "IH_COMM_GREATER" DOUBLE,
 "OS_COMM_LESSPER" DOUBLE,
 "OS_COMM_LESS" DOUBLE,
 "OS_COMM_GREATERPER" DOUBLE,
 "OS_COMM_GREATER" DOUBLE,
 "OS_PL" VARCHAR(2),
 "IH_MINELIGPER" DOUBLE,
 "OS_MINELIGPER" DOUBLE,
 "LAST_CHGDATE" DATETIME,
 "LAST_CHGBY" VARCHAR(10));
